apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: dockersubodh/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
