apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
  namespace: webapp
spec:
  selector:
    app: webapp-deployment
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
